# Chepter 4--------Working with number in python --------

#Number DataTYPE

# Intenger datatype   # Flooting point Datatype

# Geting the type of numaricla value--
# X = 30
# print(type(X))
# B = 3.0004
# print(type(B))


# Python number methoods-----

# Getting the abs value of a variabl
Nahid = abs(int(input("Enter the value of Nahid : ")))
print(Nahid)
# print(abs(Nahid))

#Rounding a variable
# n = 300.6005
# print(type(n))
# Round 
# A = float(input("Enter the value of A : "))
# Y = round(A,4)
# print(Y)

#Getting the superscribe result of a vari able

# Power
X = float(input("Enter the value of X : "))
Y = float(input("Enter the value of Y : "))
Z = float(input("Enter the value of Z : "))
print(pow(X,3))

# ভাগফল এবং ভাগশেষ

print(divmod(Y,7))
print(85*7)